### ISSUE TITLE
当运行wecos的时候，总是得到You do not have permission to get URL from this server的错误

### ISSUE THREAD

**Issue by martin-sun** [tencentyun/wecos#1]
我有一个模拟知乎的微信小程序，https://github.com/RebeccaHanjw/weapp-wechat-zhihu
我想用这个小程序来做测试，
我把知乎demo小程序放在这样的目录下：
/Users/*******/WechatProgram/weapp-wechat-zhihu
在小程序目录同级下创建wecos.config.json文件
{
  "appDir": "./weapp-wechat-zhihu",
  "backupDir": "./wecos_backup",
  "uploadFileSuffix": [".jpg",".png",".gif",".webp"],
  "compress": true,
  "cos": {
    "appid": "1252412068",
    "bucketname": "zhihutest",
    "folder": "/", //资源存放在bucket的哪个目录下
    "region": "hb", //创建bucket时选择的地域简称
    "secret_key": "****************************",
    "secret_id": "****************************"
  }
}，

同时在万象优图的默认项目里建立了zhihutest 的bucket。
当我运行wecos 的时候就会得到这样的错误信息：
watchList [ 'weapp-wechat-zhihu/**/*.jpg',
  'weapp-wechat-zhihu/**/*.png',
  'weapp-wechat-zhihu/**/*.gif',
  'weapp-wechat-zhihu/**/*.webp' ]
uploadBlackList []
/***** 【微信cos瘦身工具】 start watching *****/
/***** 【Listening App path】 weapp-wechat-zhihu  *****/
⠴ upload: weapp-wechat-zhihu/images/zhi.pngundefined:1
You do not have permission to get URL '/files/v2/1252412068/zhihutest/%2Fimages%2F24213.jpg' from this server.
^

SyntaxError: Unexpected token Y
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wecos/lib/common.js:82:19)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

请看看到底是我的配置问题还是有bug存在？

**Comment by Galen-Yip** [comment]
@martin-sun 从错误提示看，你试一下去COS控制台开启CDN加速域名

**Comment by martin-sun** [comment]
@Galen-Yip 谢谢你的答复， 我的cnd是打开的。一样的错误。
![image](https://cloud.githubusercontent.com/assets/6938330/24415906/3b132da6-13a0-11e7-899c-fa82fde6cf20.png)
![image](https://cloud.githubusercontent.com/assets/6938330/24415931/47b72c38-13a0-11e7-9928-ebfb5ad2b80c.png)
![image](https://cloud.githubusercontent.com/assets/6938330/24416016/8eda16ac-13a0-11e7-99b7-4776cca4d653.png)

为什么这个URL 是  '/files/v2/1252412068/zhihutest/%2Fimages%2F24213.jpg' from this server. 我觉的这个URL是有问题的。

**Comment by Galen-Yip** [comment]
不好意思哈 之前没留意到 回复晚了 
你看下配置里面那个region字段 应该是填错了的 
你这个bucket在天津 应该写成tj

**Comment by martin-sun** [comment]
@Galen-Yip ，谢谢指点，我把这个bucket的region字段改成tj了，已经能够成功上传图片到云服务器了。
就是想问一下，我在配置中只能找到华北 的地区，但我怎么知道是 天津？
